// Direct deposit/app URLs for each protocol slug from DefiLlama
// Fallback is the DefiLlama pool page when no direct URL is known.

const PROTOCOL_URLS: Record<string, string> = {
  // ── Lending / Money Markets ──────────────────────────────────────────
  "aave-v3":                "https://app.aave.com/",
  "aave-v2":                "https://app.aave.com/",
  "aave-v1":                "https://app.aave.com/",
  "compound-v3":            "https://app.compound.finance/",
  "compound-v2":            "https://app.compound.finance/",
  "spark":                  "https://app.spark.fi/",
  "morpho":                 "https://app.morpho.org/",
  "morpho-blue":            "https://app.morpho.org/",
  "morpho-aave-v3":         "https://app.morpho.org/",
  "morpho-aave-v2":         "https://app.morpho.org/",
  "morpho-compound":        "https://app.morpho.org/",
  "euler":                  "https://app.euler.finance/",
  "euler-v2":               "https://app.euler.finance/",
  "venus":                  "https://app.venus.io/markets",
  "benqi":                  "https://app.benqi.fi/markets",
  "radiant-v2":             "https://app.radiant.capital/",
  "radiant-v1":             "https://app.radiant.capital/",
  "ironbank":               "https://app.ib.xyz/",
  "cream":                  "https://app.cream.finance/",
  "silo-finance":           "https://app.silo.finance/",
  "silo-v2":                "https://app.silo.finance/",
  "notional-v2":            "https://notional.finance/",
  "notional-v3":            "https://notional.finance/",
  "exactly":                "https://exact.ly/",
  "ionic-protocol":         "https://app.ionic.money/",
  "seamless-protocol":      "https://app.seamlessprotocol.com/",
  "dolomite":               "https://app.dolomite.io/",
  "gearbox":                "https://app.gearbox.fi/",
  "clearpool":              "https://clearpool.finance/",
  "maple":                  "https://app.maple.finance/",
  "goldfinch":              "https://app.goldfinch.finance/earn",
  "sturdy":                 "https://v2.sturdy.finance/",
  "fluid":                  "https://fluid.instadapp.io/",
  "lendle":                 "https://lendle.xyz/",
  "mendi-finance":          "https://mendi.finance/",
  "moonwell":               "https://moonwell.fi/discover",
  "granary":                "https://granary.finance/",
  "wepiggy":                "https://wepiggy.com/",
  "uwu-lend":               "https://uwulend.fi/",
  "fraxlend":               "https://app.frax.finance/fraxlend",
  "blur-lending":           "https://blur.io/lending",
  "pac-finance":            "https://www.pac.finance/",
  "colend":                 "https://app.colend.xyz/",

  // ── Liquid Staking ──────────────────────────────────────────────────
  "lido":                   "https://stake.lido.fi/",
  "rocket-pool":            "https://stake.rocketpool.net/",
  "frax-ether":             "https://app.frax.finance/frxeth/mint",
  "stader":                 "https://www.staderlabs.com/eth/stake/",
  "ankr":                   "https://www.ankr.com/staking/stake/",
  "stakewise-v3":           "https://app.stakewise.io/",
  "stakewise":              "https://app.stakewise.io/",
  "swell":                  "https://app.swellnetwork.io/stake",
  "mantle-staking":         "https://mantlenetwork.io/stake",
  "ether.fi":               "https://app.ether.fi/stake",
  "renzo":                  "https://app.renzoprotocol.com/stake",
  "puffer-finance":         "https://app.puffer.fi/restake",
  "kelp-dao":               "https://app.kelpdao.xyz/restake/",
  "eigenlayer":             "https://app.eigenlayer.xyz/",
  "dinero":                 "https://www.dinero.xyz/",
  "meta-pool":              "https://metapool.app/stake",

  // ── DEX / AMM / Liquidity ────────────────────────────────────────────
  "uniswap-v3":             "https://app.uniswap.org/pool",
  "uniswap-v2":             "https://app.uniswap.org/pool",
  "curve":                  "https://curve.fi/#/ethereum/pools",
  "curve-dex":              "https://curve.fi/#/ethereum/pools",
  "balancer":               "https://app.balancer.fi/",
  "balancer-v2":            "https://app.balancer.fi/",
  "sushiswap":              "https://app.sushi.com/pool",
  "pancakeswap":            "https://pancakeswap.finance/liquidity",
  "pancakeswap-v3":         "https://pancakeswap.finance/liquidity",
  "camelot":                "https://app.camelot.exchange/liquidity",
  "camelot-v3":             "https://app.camelot.exchange/liquidity",
  "velodrome-v2":           "https://app.velodrome.finance/deposit",
  "velodrome":              "https://app.velodrome.finance/deposit",
  "aerodrome":              "https://aerodrome.finance/deposit",
  "thena":                  "https://www.thena.fi/liquidity",
  "ramses-v2":              "https://www.ramses.exchange/liquidity",
  "ramses":                 "https://www.ramses.exchange/liquidity",
  "solidly-v3":             "https://solidly.com/liquidity",
  "maverick":               "https://app.mav.xyz/",
  "maverick-v2":            "https://app.mav.xyz/",
  "kyberswap":              "https://kyberswap.com/pools",
  "kyberswap-elastic":      "https://kyberswap.com/pools",
  "trader-joe":             "https://traderjoexyz.com/pool",
  "trader-joe-v2":          "https://traderjoexyz.com/pool",
  "wombat-exchange":        "https://app.wombat.exchange/pool",
  "orca":                   "https://www.orca.so/pools",
  "raydium":                "https://raydium.io/liquidity/",
  "ambient-finance":        "https://ambient.finance/",
  "nile":                   "https://www.nile.build/liquidity",
  "sterling":               "https://www.sterlingprotocol.com/",
  "swapbased":              "https://swapbased.finance/#/pool",
  "chronos":                "https://app.chronos.exchange/liquidity",
  "synthswap":              "https://synthswap.io/pool",
  "solidly":                "https://solidly.com/liquidity",
  "equalizer":              "https://equalizer.exchange/liquidity",
  "scale":                  "https://www.scaledex.xyz/liquidity",
  "cleopatra":              "https://www.cleopatra.exchange/liquidity",
  "cleo-exchange":          "https://www.cleopatra.exchange/liquidity",
  "fenix":                  "https://www.fenixfinance.io/liquidity",
  "dragonswap":             "https://dragonswap.app/pool",
  "kim":                    "https://app.kim.exchange/pool",
  "lynex":                  "https://app.lynex.fi/liquidity",
  "retro":                  "https://retro.finance/liquidity",
  "pearl":                  "https://www.pearl.exchange/liquidity",
  "stableswap":             "https://stableswap.finance/",

  // ── Yield Optimizers / Vaults ────────────────────────────────────────
  "yearn-finance":          "https://yearn.fi/vaults",
  "beefy":                  "https://app.beefy.com/",
  "convex-finance":         "https://www.convexfinance.com/stake",
  "concentrator":           "https://concentrator.aladdin.club/",
  "aura":                   "https://app.aura.finance/",
  "harvest-finance":        "https://app.harvest.finance/",
  "badger-dao":             "https://app.badger.com/vaults",
  "idle":                   "https://app.idle.finance/",
  "origin-dollar":          "https://app.ousd.com/",
  "origin-ether":           "https://app.oeth.com/",
  "overnight-fi":           "https://overnight.fi/app/arbitrum/earn",
  "extra-finance":          "https://app.extrafi.io/farm",
  "gmd-protocol":           "https://gmd.io/vault",
  "jones-dao":              "https://jonesdao.io/vaults",
  "plutus-dao":             "https://app.plutusdao.io/vaults",
  "dopex":                  "https://app.dopex.io/",
  "ribbon-finance":         "https://app.ribbon.finance/v2/theta-vaults",
  "factor":                 "https://app.factor.fi/",
  "pendle":                 "https://app.pendle.finance/trade/pools",
  "pirex-eth":              "https://pirex.io/",
  "dinamo":                 "https://app.dinamo.fi/",
  "cian":                   "https://cian.app/",
  "equilibria":             "https://equilibria.fi/pool",

  // ── Cross-chain / Bridge Liquidity ───────────────────────────────────
  "stargate":               "https://stargate.finance/pool",
  "stargate-v2":            "https://stargate.finance/pool",
  "hop-protocol":           "https://app.hop.exchange/#/pool",
  "across-protocol":        "https://across.to/pool",
  "synapse":                "https://synapseprotocol.com/pools",
  "multichain":             "https://app.multichain.org/",
  "celer":                  "https://cbridge.celer.network/liquidity",

  // ── Perps / Structured Products ─────────────────────────────────────
  "gmx":                    "https://app.gmx.io/#/earn",
  "gmx-v2":                 "https://app.gmx.io/#/earn",
  "gains-network":          "https://gains.trade/vaults",
  "kwenta":                 "https://kwenta.eth.limo/earn",
  "synthetix":              "https://staking.synthetix.io/pools",
  "lyra-finance":           "https://app.lyra.finance/vaults",
  "premia":                 "https://app.premia.finance/vaults",
  "umami-finance":          "https://umami.finance/vaults",

  // ── Real World Assets / CDP ──────────────────────────────────────────
  "ondo-finance":           "https://ondo.finance/ousg",
  "makerdao":               "https://app.spark.fi/",
  "sky":                    "https://app.sky.money/",
  "frax":                   "https://app.frax.finance/",
  "liquity":                "https://www.liquity.org/",
  "liquity-v2":             "https://www.liquity.org/",
  "angle":                  "https://app.angle.money/",
  "reserve":                "https://app.reserve.org/",

  // ── Solana ───────────────────────────────────────────────────────────
  "kamino":                 "https://app.kamino.finance/",
  "kamino-lend":            "https://app.kamino.finance/lend",
  "marginfi":               "https://app.marginfi.com/lend",
  "solend":                 "https://solend.fi/dashboard",
  "drift":                  "https://app.drift.trade/vaults",
  "save":                   "https://save.finance/",
  "meteora":                "https://app.meteora.ag/pools",
  "lifinity":               "https://lifinity.io/pools",
  "hawksight":              "https://app.hawksight.co/",

  // ── Bitcoin L2 / other ───────────────────────────────────────────────
  "lombard":                "https://app.lombard.finance/",
  "bedrock":                "https://app.bedrock.technology/",
  "pstake":                 "https://pstake.finance/",
  "stroom":                 "https://stroom.network/",
}

/**
 * Returns the direct deposit/app URL for a protocol.
 * Falls back to the DefiLlama pool page if the protocol is unknown.
 */
export function getProtocolUrl(project: string, poolId: string): string {
  return PROTOCOL_URLS[project] ?? `https://defillama.com/yields/pool/${poolId}`
}

/**
 * Returns true when we have a known direct URL (not a DefiLlama fallback).
 */
export function hasDirectUrl(project: string): boolean {
  return project in PROTOCOL_URLS
}
